version: '2'

services:

  php:
    build: .
    volumes: ['./:/app']
    env_file: ['.env']

  composer:
    extends: { service: php }
    entrypoint: ['composer']

  phpunit:
    extends: { service: php }
    entrypoint: ['./vendor/bin/phpunit']

